#!/bin/bash

#pre-requisites on host
apt-get install obexftp libopenobex1-dev libusb-dev

#obex-ftp
apt-get source libusb-dev
apt-get source libopenobex1-dev
apt-get source obexftp

#obex-fs
wget -c -O fuse-2.9.3.tar.gz downloads.sourceforge.net/project/fuse/fuse-2.X/2.9.3/fuse-2.9.3.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Ffuse%2F%3Fsource%3Dtyp_redirect&ts=1409211723&use_mirror=cznic &&
wget -c pkgs.fedoraproject.org/repo/pkgs/obexfs/obexfs-0.12.tar.gz/0f505672b025cdb505e215ee707a2e2f/obexfs-0.12.tar.gz

#removing junk
rm -rf *dsc* *diff* *debian* *orig* *ubuntu*
